---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0  # Or your desired MySQL image tag
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "your_secure_root_password"  # Replace with a secure value or use a Secret
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql  # Standard MySQL data directory inside the container
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-dados  # Connects to the PersistentVolumeClaim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP  # Or LoadBalancer if you need external access